name: dfpl_env
channels:
  - conda-forge
  - defaults
dependencies:
  # dev requirements
  - conda-build>=3.21.8
  - conda>=4.12.0
  - pip>=22.0.4
  - pytest>=7.1.1
  - python=3.8
  # application requirements
  - protobuf>=3.21.12
  - jsonpickle>=2.1
  - matplotlib>=3.5.1
  - numpy=1.23.5
  - rdkit>=2023.03.3
  - scikit-learn>=1.0.2
  - seaborn>=0.12.2
  - tensorflow>=2.13
  - wandb>=0.16.2
  - umap-learn=0.5.5
  - numba>=0.51.0
  - pip:
    - git+https://github.com/soulios/chemprop.git@cfcb67a


