name: Build DFPL Singularity Container
on: [push]
jobs:

  build:
    name: Install Base System
    runs-on: ubuntu-20.04
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Install Dependencies
      run: |
        sudo apt-get update && sudo apt-get install -y build-essential \
          libssl-dev \
          uuid-dev \
          libgpgme11-dev \
          squashfs-tools \
          libseccomp-dev \
          wget \
          pkg-config \
          git \
          cryptsetup
        sudo apt-get clean

    - name: Install Singularity
      env:
        SINGULARITY_VERSION: 3.6.3
        GOPATH: /tmp/go
      run: |
        mkdir -p $GOPATH
        sudo mkdir -p /usr/local/var/singularity/mnt && \
        mkdir -p $GOPATH/src/github.com/sylabs && \
        cd $GOPATH/src/github.com/sylabs && \
        wget -qO- https://github.com/sylabs/singularity/releases/download/v${SINGULARITY_VERSION}/singularity-${SINGULARITY_VERSION}.tar.gz | \
        tar xz && \
        cd singularity && \
        ./mconfig -p /usr/local && \
        make -C builddir && \
        sudo make -C builddir install
        cd ..
        rm -rf singularity

    - name: Fetch DFPL Code from GitHub
      uses: actions/checkout@v1

    - name: Build DFPL Singularity Container
      env:
        SINGULARITY_RECIPE: singularity_container/dfpl.def
        OUTPUT_CONTAINER: dfpl.sif
      run: |
       if [ -f "${SINGULARITY_RECIPE}" ]; then
           cd $(dirname ${SINGULARITY_RECIPE})
           sudo singularity build ${OUTPUT_CONTAINER} $(basename ${SINGULARITY_RECIPE})
           echo "${SINGULARITY_RECIPE} built successfully"
       else
           echo "${SINGULARITY_RECIPE} is not found."
           echo "Present working directory: $PWD"
       fi
    - name: Deploy DFPL Container to Sylabs
      env:
        SINGULARITY_TOKEN: ${{ secrets.SINGULARITY_TOKEN }}
        SINGULARITY_CONTAINER: singularity_container/dfpl.sif
      run: |
        echo ${SINGULARITY_TOKEN} | singularity remote login
        singularity remote status
        singularity push -U ${SINGULARITY_CONTAINER} library://mai00fti/default/dfpl.sif:latest

